server:
  host: "0.0.0.0"
  port: "8080"
  static_dir: "./static"
  permission: "0644"
  mode: "create"

logging:
  level: "INFO"

auth:
  private_key_path: ""
  access_token_ttl: "15m"
  refresh_token_ttl: "168h"
  admin_password: ""
  guest_password: ""